version: '3.4'

services:
  front:
    image: front
    build:
      context: front
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]

  jwtauthapi:
    image: jwtauthapi
    build:
      context: .
      dockerfile: back/JWTAuth.Api/Dockerfile
    ports:
      - 5166:5166
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
