version: '3.4'

services:
  front:
    image: front
    build:
      context: front
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  
  jwtauthapi:
    image: jwtauthapi
    build:
      context: .
      dockerfile: back/JWTAuth.Api/Dockerfile
    ports:
      - 5166:5166
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - jwtauthdb:/db
    ports:
      - 1401:1433
    container_name: mssql
  
volumes:
  jwtauthdb: {}